### ISSUE TITLE
breaking semver and my sites

### ISSUE THREAD

**Issue by relvao** [linkedin/dustjs-helpers#115]
If you decide to deprecate the @if helper shouldn't you release version 2.0.0 instead of 1.6.0?

**Comment by sethkinast** [comment]
`{@if}` and `{@idx}` were actually deprecated in 1.5. They spewed log messages when they were invoked, warning you that they would be removed in a future version. We promise to never remove a feature without first deprecating it for one full minor release.

1.5 is fully compatible with Dust 2.6 as part of our commitment to support N+1 for every helpers release in a major version, so it's totally OK to keep using 1.5 with Dust 2.6.

Dust and its helpers do not follow semantic versioning (and never have). We definitely recommend pinning something as important as your template engine at a minor version using a construct like:

    "dustjs-helpers": "~1.5"

**Comment by relvao** [comment]
Thanks. My bad. 

By default I install  modules with '--save' or '--save-dev' which assumes semver and updates to a compatible version, which is clearly not the case with this one. Had a little surprise this morning when I uploaded a project to its server.
