### ISSUE TITLE
@default and @none helpers not working properly on 1.6.0 version

### ISSUE THREAD

**Issue by vemahendran** [linkedin/dustjs-helpers#121]
After upgrading dustjs-helpers@1.6.0, the parameter section is not populated on `@default` and `@none` helpers. For example,

```
{#data.messages tmp=data}
    {@select key="{message}"}
        {@eq value="done"}
            <p>{data}</p>
            <p>{tmp}</p>
        {/eq}
        {@default}
            <p>{data}</p>
            <p>{tmp}</p>
        {/default}
    {/select}
{/data.messages}
```
Here, both `{data}` and `{tmp}` are not pouplated within `@default` helper. Same thing is applicable to `@none` helper

Ref: parameter section - https://github.com/linkedin/dustjs/wiki/Dust-Tutorial#sections-with-parameters

**Comment by jimmyhchan** [comment]
Thanks for reporting and thanks for the simplified example!  investigating.

**Comment by jimmyhchan** [comment]
actually. can you elaborate on structure of data.

is it 
```
{data: [{messages: ['a','b','c']},{messages: ['a','b','c']},{messages: ['a','b','c']}]}
```

or do yo have some nested thing with multiple "data" properties.

**Comment by jimmyhchan** [comment]
seems to be related to eb1083981d1d5abcc1622b2c3caa02118def870e. I'm still trying to get this reproduced.

**Comment by sethkinast** [comment]
`addSelectState` seems like it'd be the culprit but we have tests around much of this stuff, so must be an edge case somewhere.

**Comment by jimmyhchan** [comment]
confirmed the issue. we are dropping the tail context somewhere

here's a simplified test. 

works in 1.5
fails in 1.6

```
+        name:     "select helper inside a array reaching outside",
+        source:   ["{#skills}{@select key=\"{.}\"}",
+                   "{@eq value=\"java\"}JAVA {outside},{/eq}",
+                   "{@eq value=\"js\"}JS {outside},{/eq}",
+                   "{@default value=\"foo\"}UNKNOWN {outside}{/default}",
+                   "{/select}{/skills}"].join("\n"),
+        context:  { "skills" : [ "java", "js" , "unknown"], "outside": 'foo' },
+        expected: "JAVA foo,JS foo,UNKNOWN foo",
+        message: "should test select helper inside a array with {.} and reaches outside"
```

**Comment by jimmyhchan** [comment]
OK i found the issue.

`context.rebase`... doesn't do what you think it does. It takes a `head` and not a `tail`. the add function is adding a tail into a head which doesn't work.

**Comment by sethkinast** [comment]
So I want context.stack.tail.head?

**Comment by jimmyhchan** [comment]
nahh it's more annoying then that.

**Comment by sethkinast** [comment]
There's a possible fix, but I want to look into it a bit more to make sure there aren't more edge cases.

**Comment by sethkinast** [comment]
Yeah, this isn't enough. {$idx} has problems.

**Comment by sethkinast** [comment]
There we go.

**Comment by sethkinast** [comment]
1.6.1 released with a fix. Thank you again for the report!
