### ISSUE TITLE
Don't require a key for {@select}

### ISSUE THREAD

**Issue by sethkinast** [linkedin/dustjs-helpers#123]
Based on http://stackoverflow.com/a/29151097/938516

If you have to do truth tests on several variables but you want to group the tests for the purposes of `any` / `none` / `default` it's a little more readable to attach variables directly to their truth tests.

If we made this change, though, it moves even further away from the semantics of select-as-switch. Select basically becomes a "grouped truth test".

Any thoughts?

**Comment by rragan** [comment]
I recall suggesting this omission back when the @or variant was under discussions. Too bad we have the @select legacy meaning. Simple alias of @or?

**Comment by jimmyhchan** [comment]
(aside)FYI, the `@'s` are mentions referring to github individuals.  Please use the back ticked `at` instead.(aside)

**Comment by sethkinast** [comment]
I don't like adding a new tag that's just an alias-- that seems to bloat the API.

If we were changing the semantics of select, I could definitely see introducing a new tag and deprecating the old one, but it's really just relaxing a restriction.

If that's weird, I'm totally OK saying that you just have to have a key :)

**Comment by rragan** [comment]
I'm ok keeping it with select and making the optional

**Comment by prashn64** [comment]
I agree with this
