### ISSUE TITLE
@select fails to render multiple @eq statements inside a @none block

### ISSUE THREAD

**Issue by cstigler** [linkedin/dustjs-helpers#139]
If you place multiple **satisfied** ```@eq``` statements inside of a ```@none``` block inside of a ```@select```, all except the first one will fail to render (i.e. the page will rendered but they will not be displayed). This is reproducible on the official [Dust.js test page](http://linkedin.github.io/dustjs/test/test.html) with dustjs 2.7.2 and dustjs-helpers 1.7.2

Test Case
-------------

Template:
```
{@select key="{targetCity}"}
	{@none}
		{! if this @eq statement is called (favoriteAnimal is tiger) it will break the next one !}
		{@eq key="{favoriteAnimal}" value="tiger"}
		{/eq}

		{! favoriteInstrument is violin, but this is not rendered! !}
		{@eq key="{favoriteInstrument}" value="violin"}
			<span>*** Instrument is violin! ***</span>
		{/eq}
	{/none}
{/select}
```

Context:
```
{
	targetCity: 'nyc',
	favoriteAnimal: 'tiger',
	favoriteInstrument: 'violin'
}
```

Debugging
---------------

I traced the problem down to [this commit](https://github.com/linkedin/dustjs-helpers/commit/fa6a8ea57e2fb13c6785e9644678c6f990a9835b) from April 17th, just before the release of 1.7.0. Specifically, line 111 in the ```filter``` function seems to be the problem, where this was added:

```
// Once one truth test in a select passes, short-circuit the rest of the tests
if (selectState.isResolved) {
    return chunk;
}
```

I'm guessing that since we're still in the select, we're improperly short-circuiting everything instead of just the other select options.

I may try to submit a PR, but I'm a newbie to this library so if you see a clean solution you may be able to solve it much more quickly! Or if you have a suggested implementation strategy, let me know and I can implement it. Thanks for the library.

**Comment by sethkinast** [comment]
Thanks for the great report.

I won't be able to look into this for a couple days so PRs are definitely always welcome. You are looking in the correct section of the code :)

If you fix the issue, run `npm test` to make sure all the tests pass, and maybe add a new one in `test/jasmine-test/spec/helpersTests.js` if you could.

Otherwise I'll take a look this weekend or so!

**Comment by sethkinast** [comment]
There's a "pending" state once the select is about to be resolved:

```
    // Once a truth test passes, put the select into "pending" state. Now we can render the body of
    // the truth test (which may contain truth tests) without altering the state of the select.
    if (!selectState.isPending) {
```

Probably we need to set pending during the execution of `none` and maybe `any` blocks as well.

**Comment by sethkinast** [comment]
I think this is an expedient fix, but I really want to rewrite the way select states are handled now that we have context options.

I'll let this bake a day or so before releasing a patch version so I can check more edge cases.

**Comment by cstigler** [comment]
@sethkinast Thanks for taking a look so quickly! 👍 I was just trying to figure the system out when I saw that. That solution seems clean/correct to me, although I don't know much about potential refactoring options. We'll be looking forward to a merge/release whenever it comes!

**Comment by sethkinast** [comment]
Yep I'll bug someone to +r tomorrow and give you a patch release before the
weekend

On Wed, Jul 22, 2015 at 5:54 PM, Charlie Stigler <notifications@github.com>
wrote:

> @sethkinast <https://github.com/sethkinast> Thanks for taking a look so
> quickly! 👍 I was just trying to figure the system out when I saw that.
> That solution seems clean/correct to me, although I don't know much about
> potential refactoring options. We'll be looking forward to a merge/release
> whenever it comes!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/dustjs-helpers/issues/139#issuecomment-123919183>
> .
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by sethkinast** [comment]
Sorry for the delay, cutting a new patch release now

**Comment by cstigler** [comment]
@sethkinast Thank you! Working great now.
