### ISSUE TITLE
Add case-insensitive {@eq} comparator

### ISSUE THREAD

**Issue by sethkinast** [linkedin/dustjs-helpers#142]
Per http://stackoverflow.com/questions/35438743/how-do-i-check-case-insensitive-values-in-dust-js

This seems to be pretty reasonable. It could be a new type instead of a second param to eq. What's a good name for this type?

**Comment by smfoote** [comment]
`{@double-eq}`?

**Comment by sethkinast** [comment]
This would just be a `type` on `{@eq}`, like `{@eq type="case-insensitive-string"}` (which is too long :P )

**Comment by sethkinast** [comment]
`istring`?

**Comment by smfoote** [comment]
`{@eq flags="i"}`

**Comment by sethkinast** [comment]
I don't like introducing a new flags param that would only apply to strings, since eq compares anything.

**Comment by smfoote** [comment]
Good point. Maybe this should be a separate helper? Otherwise "istring" looks pretty good. Although it looks like `isString` at first glance.

**Comment by sethkinast** [comment]
What about something around loose vs strict, where loose matches with
double eq and case insensitive, and strict is what we have? That could be
its own flag or own helper.

**Comment by sethkinast** [comment]
```
{@eq key="0" value=0 strict="false"}true{/eq}
{@ne key="0" value=0}default is strict, just like now{/ne}
{@eq key="Alice" value="alice" strict="false"}maybe it's weird that strict means both double-eq and toLower{/eq}```

**Comment by sethkinast** [comment]
`{@eq key="3.1" value=3 strict="false"}how deep does it go{/eq}`

**Comment by smfoote** [comment]
`{@eq key="What is the answer?" value=42 strict="false"}Turtles all the way down{/eq}`

**Comment by prashn64** [comment]
We should be making it easier to transform inputs instead of adding flags to our comparators. So like if we had a toLowerCase helper or mathFloor helper that we could use inside our eq/ne helpers, we can handle more cases

**Comment by sethkinast** [comment]
A filter totally seems like the right solution, and one that people could
add themselves. Nice call.
