### ISSUE TITLE
@eq helper doesn't work when accessing an object at a deeper level

### ISSUE THREAD

**Issue by AndySDH** [linkedin/dustjs-helpers#145]
Given this context:
`{"attr":{"ct1":{"value":["Mick"]}}}`

This code

```
 {#attr}
        {#ct1}
           {@eq key=value value="Mick"}
              It should be true
          {:else}
              But it's false
          {/eq}
        {/ct1}
    {/attr}
```

should return True. But it returns False for some reason.

Same thing for this variant:
```
 {@eq key=attr.ct1.value value="Mick"}
              It should be true
          {:else}
              But it's false
          {/eq}
```

The weird thing is, that if you change it to @gte instead of @eq, it returns True correctly. So the problem seems to only happen with @eq. Am I missing something or is it a bug?

**Comment by rashad612** [comment]
In your `ctx` `value` is an array. You're trying to compare the values between a string and an array. Your `ctx` should be something like this:

```js
{"attr":{"ct1":{"value":"Mick"}}}
```

**Comment by AndySDH** [comment]
> In your ctx value is an array. You're trying to compare the values between a string and an array. 
@rashad612 Uuuuuuuh I see. Thanks for clarifying that. That makes sense.
For curiosity, is there anyway to compare whether a string is contained in an array?
Thanks again!

**Comment by rashad612** [comment]
The simples way, in JavaScript is using `indexOf`:
```js
// Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf
var a = [2, 9, 9]; 
a.indexOf(2); // 0 
a.indexOf(7); // -1

if (a.indexOf(7) === -1) {
  // element doesn't exist in array
}
// otherwise it exists
```

To have this worked in Dust, you might need to write your own Dust helper, containing the previous snippet. Please refer to **AddingNewHelpers** here: http://www.dustjs.com/guides/dust-helpers/

**Comment by fpreti** [comment]
Hi!
i have the same issue, @eq don't work properly.
In my case user.GRUPPO it's a string but {@eq key=user.GRUPPO value="STEP2"}{/eq} return false (the value of user.GRUPPO it's STEP2) :-)

thanks

**Comment by rashad612** [comment]
@fpreti, how about this?

```
{#user}
{@eq key="GRUPPO" value="STEP2"}{/eq}
{/user}
```

**Comment by fpreti** [comment]
Hi, @rashad612 
i think that this issue can be marked closed, i tried with your solution and works fine!

Thank you
