### ISSUE TITLE
Peaceful coexistence of user-supplied helpers

### ISSUE THREAD

**Issue by rragan** [linkedin/dustjs-helpers#32]
Currently, the dust-helper.js implementation will blow away any existing dust.helpers the user may have created. Could the code be a bit more tolerant and add the standard ones to an existing dust.helpers if it already  exists. 

I guess one could assert that the dependency order needs to be gotten correct and then this is not an issue but it adds another trap people can fall into.

**Comment by sethkinast** [comment]
Helpers no longer clobber `dust.helpers` as of 1.6.0.
